# Generated by Django 4.1.3 on 2023-05-02 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shoes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.CharField(max_length=10)),
                ('product_category', models.CharField(max_length=50)),
                ('product_name', models.CharField(max_length=100)),
                ('availability', models.CharField(max_length=15)),
                ('price', models.CharField(max_length=10)),
                ('image', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'shoes',
                'db_table': 'shoes',
                'managed': True,
            },
        ),
    ]
