# Generated by Django 4.1.3 on 2023-05-03 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=50)),
                ('ship_id', models.CharField(max_length=50)),
                ('product_id', models.CharField(max_length=50)),
                ('product_name', models.CharField(max_length=100)),
                ('quantity', models.CharField(max_length=5)),
                ('price', models.CharField(max_length=10)),
            ],
        ),
    ]
