# Generated by Django 4.1.3 on 2023-05-03 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order_model', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='order',
            table='order',
        ),
    ]
