# Generated by Django 4.1.3 on 2023-05-02 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.CharField(max_length=50)),
                ('username', models.CharField(max_length=50)),
                ('product_category', models.CharField(max_length=50)),
                ('product_name', models.CharField(max_length=100)),
                ('count', models.CharField(max_length=5)),
                ('totalprice', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'cart',
            },
        ),
    ]
